### ISSUE TITLE
discrepancy of instructions between README and study.md

### ISSUE THREAD

**Issue by BenGitsCode** [ga-wdi-boston/js-javascripting-study#14]
I didn't realize this myself until now, the readme asks for a standard pull request response, and the study.

We should clarify directions between the two to be more clear an uniform.

**Comment by jrhorn424** [comment]
Possible duplicate of #2

**Comment by BenGitsCode** [comment]
Definitely a duplicate of #2 just unclear on what the decision is. A lot of developers seemed confused between the study and readme though antony slacked them a link to the study.md saying to follow those instructions, which should be clear.
