### ISSUE TITLE
var instead of let

### ISSUE THREAD

**Issue by MishaHerscu** [ga-wdi-boston/js-javascripting-study#6]
I am not sure if this is a big deal, but should we make this ask us to use `let` instead of `var` since that is what we are doing in class?

**Comment by laurenfazah** [comment]
@gaand @jrhorn424 do we want to take action on this? While we can't change javascripting's core instructions, we could instruct developers to complete assignments in strict mode.

**Comment by laurenfazah** [comment]
@gaand: I just spoke with @jrhorn424 about this. Going to instruct developers to complete assignments in strict mode.
